//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foundry.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foundry.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _lock {
            get {
                object obj = ResourceManager.GetObject("_lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arrow_refresh_small {
            get {
                object obj = ResourceManager.GetObject("arrow_refresh_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap box {
            get {
                object obj = ResourceManager.GetObject("box", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;name&quot;: &quot;CanGetUnits&quot;,
        ///    &quot;inputs&quot;: [
        ///      {
        ///        &quot;name&quot;: &quot;FilterPlayer&quot;,
        ///        &quot;valueType&quot;: &quot;Player&quot;,
        ///        &quot;optional&quot;: true,
        ///        &quot;sigId&quot;: 3
        ///      },
        ///      {
        ///        &quot;name&quot;: &quot;FilterPlayerList&quot;,
        ///        &quot;valueType&quot;: &quot;PlayerList&quot;,
        ///        &quot;optional&quot;: true,
        ///        &quot;sigId&quot;: 10
        ///      },
        ///      {
        ///        &quot;name&quot;: &quot;FilterObjectType&quot;,
        ///        &quot;valueType&quot;: &quot;ObjectType&quot;,
        ///        &quot;optional&quot;: true,
        ///        &quot;sigId&quot;: 4
        ///      },
        ///      {
        ///        &quot;name&quot;: &quot;FilterLocation&quot;,
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cnd {
            get {
                return ResourceManager.GetString("cnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap discord {
            get {
                object obj = ResourceManager.GetObject("discord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;name&quot;: &quot;TriggerActivate&quot;,
        ///    &quot;inputs&quot;: [
        ///      {
        ///        &quot;name&quot;: &quot;Trigger&quot;,
        ///        &quot;valueType&quot;: &quot;Trigger&quot;,
        ///        &quot;optional&quot;: false,
        ///        &quot;sigId&quot;: 1
        ///      }
        ///    ],
        ///    &quot;outputs&quot;: [],
        ///    &quot;sources&quot;: [
        ///      &quot;1.txt&quot;
        ///    ],
        ///    &quot;dbid&quot;: 31,
        ///    &quot;version&quot;: 1
        ///  },
        ///  {
        ///    &quot;name&quot;: &quot;CopyBool&quot;,
        ///    &quot;inputs&quot;: [
        ///      {
        ///        &quot;name&quot;: &quot;BoolSource&quot;,
        ///        &quot;valueType&quot;: &quot;Bool&quot;,
        ///        &quot;optional&quot;: false,
        ///        &quot;sigId&quot;: 1
        ///      }
        ///    ],
        ///    &quot;outputs&quot;: [
        ///      {
        ///        &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string eff {
            get {
                return ResourceManager.GetString("eff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_skirt {
            get {
                object obj = ResourceManager.GetObject("icon_skirt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap lock_open {
            get {
                object obj = ResourceManager.GetObject("lock_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap page {
            get {
                object obj = ResourceManager.GetObject("page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap page_white {
            get {
                object obj = ResourceManager.GetObject("page_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  &quot;Bool&quot;,
        ///  &quot;Float&quot;,
        ///  &quot;Squad&quot;,
        ///  &quot;Integer&quot;,
        ///  &quot;Player&quot;,
        ///  &quot;PlayerList&quot;,
        ///  &quot;Power&quot;,
        ///  &quot;Tech&quot;,
        ///  &quot;ObjectType&quot;,
        ///  &quot;Vector&quot;,
        ///  &quot;UnitList&quot;,
        ///  &quot;Unit&quot;,
        ///  &quot;SquadList&quot;,
        ///  &quot;Objective&quot;,
        ///  &quot;Sound&quot;,
        ///  &quot;ProtoSquad&quot;,
        ///  &quot;LocStringID&quot;,
        ///  &quot;ChatSpeaker&quot;,
        ///  &quot;Time&quot;,
        ///  &quot;TalkingHead&quot;,
        ///  &quot;Operator&quot;,
        ///  &quot;PlayerState&quot;,
        ///  &quot;Cost&quot;,
        ///  &quot;String&quot;,
        ///  &quot;ObjectDataType&quot;,
        ///  &quot;ObjectDataRelative&quot;,
        ///  &quot;CommandType&quot;,
        ///  &quot;EntityFilterSet&quot;,
        ///  &quot;Color&quot;,
        ///  &quot;DataScalar&quot;,
        ///  &quot;Object&quot;,
        ///  &quot;ObjectList&quot;,
        ///  &quot;VectorList&quot;,
        ///  &quot;Cin [rest of string was truncated]&quot;;.
        /// </summary>
        public static string var {
            get {
                return ResourceManager.GetString("var", resourceCulture);
            }
        }
    }
}
